[package]
name = "kokars-example"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = { version = "0.2.0", default-features = false }
kokars = { path = "../kokars" }
libc-print = "0.3.0"

[build-dependencies]
cbindgen = "0.29.2"

[profile.dev]
panic="abort"

[profile.release]
panic="abort"
